"""empty message

Revision ID: f95048d3b564
Revises: 
Create Date: 2025-12-30 19:18:32.837712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95048d3b564'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favortitos',
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('Fecha_de_subscripción', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile__personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('color_pelo', sa.String(), nullable=False),
    sa.Column('Sexo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['personaje.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile__planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('Tamaño', sa.Integer(), nullable=True),
    sa.Column('Distancia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile__planet')
    op.drop_table('profile__personaje')
    op.drop_table('profile')
    op.drop_table('favortitos')
    op.drop_table('user')
    op.drop_table('planet')
    op.drop_table('personaje')
    # ### end Alembic commands ###
